---
output: 
  rmarkdown::html_document:
    theme: flatly
---

<h2><b> ANALYZING COUNTY ELECTION RESULTS </b></h2>

```{r, load packages and set themes, echo=FALSE, message=FALSE, results='hide', warning=FALSE}

# Load packages
library(ggplot2, quietly = TRUE)
library(ggthemes, quietly = TRUE)
library(extrafont, quietly = TRUE)
library(scales, quietly = TRUE)
library(acs, quietly = TRUE)
library(plyr, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(rgdal, quietly = TRUE)
library(plotly, quietly = TRUE)
library(stringr, quietly = TRUE)

# Set plot theme
theme_set(
  theme_bw(base_family = 'Segoe UI', base_size = 12) +
    theme(
      plot.title = element_text(face = 'bold', hjust = 0),
      text = element_text(colour = '#445359'),
      panel.background = element_rect('#ffffff'),
      strip.background = element_rect('#ffffff', colour = 'white'),
      plot.background = element_rect('#ffffff'),
      panel.border = element_rect(colour = '#ffffff'),
      panel.grid.major.x = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      legend.background = element_rect('#ffffff'),
      legend.title = element_blank(),
      legend.position = 'right',
      legend.direction = 'vertical',
      legend.key = element_blank(),
      strip.text = element_text(face = 'bold', size = 10),
      axis.text = element_text(face = 'bold', size = 9),
      axis.title = element_blank(),
      axis.ticks = element_blank()
    )
)

```

<h2><b> Load Data & Clean </b></h2>

```{r, load data & clean, echo=FALSE, message=FALSE, results='hide', warning=FALSE}

## Pull Election Results Data
# -- https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/MLLQDH
election.results.df <- read.csv('president-wide.csv',
                                header = TRUE,
                                stringsAsFactors = FALSE)

# Take a look at the data to see what needs to be cleaned up
head(election.results.df)
glimpse(election.results.df)

## Fix FIPS codes

# States w/ leading 0s
zeroes <- c('AK', 'AL', 'AZ', 'AR', 'CA', 'CO', 'CT')

# Fix states w/ leading 0s
election.results.df2 <- election.results.df %>% 
  filter(state %in% zeroes) %>% 
  mutate(fips_fixed = paste0(0, substr(fipscode, 1, 4)))

# Fix states w/o leading 0s
election.results.df3 <- election.results.df %>% 
  filter(!(state %in% zeroes)) %>% 
  mutate(fips_fixed = substr(fipscode, 1, 5))

# Combine
election.results.df <- rbind(election.results.df2,
                             election.results.df3)

# Remove two party thing
election.results.df$dem.two.party <- NULL

# Aggregate up to county where applicable
election.results.agg <- election.results.df %>% 
  group_by(fips_fixed) %>%
  select(-one_of('office', 'state', 'jurisdiction', 'fipscode')) %>%
  summarise_each(funs(sum))

# Remove NA values
election.results.agg[is.na(election.results.agg)] <- 0

# Calculate % of vote for each candidate
election.results.agg[, c(2:6)] <- election.results.agg[, c(2:6)] / rowSums(election.results.agg[, c(2:6)])

# Bring back state and jurisdiction
election.results.final <- election.results.df %>% 
  select(fips_fixed, state, jurisdiction)

election.results.final <- left_join(election.results.agg,
                                    election.results.final, 
                                    by = 'fips_fixed')

# Write to csv
write.csv(election.results.final, 'county_results_clean.csv', row.names = FALSE)

## Pull Map Data

# Pull in shapefile
cty <- readOGR(dsn = "shapefiles", 
               layer = "tl_2010_us_county10")

cty@data$id <- rownames(cty@data)

# Convert polygons in cty to a data frame for plotting
cty.df <- fortify(cty)

# Join columns
cty.df <- merge(cty.df, 
                cty@data, 
                by = "id")

## Adding County Demographics

# Pull in county data from Census Bureau API for all states
api.key.install(key='0d49769f4920428f1240cd67d86ee8d61ebaa4bc')

# create a geographic set to grab tabular data (acs)
geo <- geo.make(state="*",
                county="*")

# Pull race data
# -- Table B02001
race <- acs.fetch(endyear = 2015, span = 5, geography = geo,
                    table.number = "B02001", col.names = "pretty")

# convert to a data.frame for merging
race_df <- data.frame(paste0(str_pad(race@geography$state, 2, "left", pad="0"), 
                               str_pad(race@geography$county, 3, "left", pad="0")), 
                        race@estimate, 
                        stringsAsFactors = FALSE)
names(race_df)[1] <- 'geoid'

# Pull employment data
# -- Table B23001
employment <- acs.fetch(endyear = 2015, span = 5, geography = geo,
                        table.number = "B23001", col.names = "pretty")

# convert to a data.frame for merging
employment_df <- data.frame(paste0(str_pad(employment@geography$state, 2, "left", pad="0"), 
                               str_pad(employment@geography$county, 3, "left", pad="0")), 
                        employment@estimate, 
                        stringsAsFactors = FALSE)
names(employment_df)[1] <- 'geoid'


# Pull income data
# -- Table B19001	
income <- acs.fetch(endyear = 2015, span = 5, geography = geo,
                        table.number = "B19001", col.names = "pretty")

# convert to a data.frame for merging
income_df <- data.frame(paste0(str_pad(income@geography$state, 2, "left", pad="0"), 
                               str_pad(income@geography$county, 3, "left", pad="0")), 
                        income@estimate, 
                        stringsAsFactors = FALSE)
names(income_df)[1] <- 'geoid'


# Pull occupation data
# -- Table B24124	
occupation <- acs.fetch(endyear = 2015, span = 5, geography = geo,
                        table.number = "B24124", col.names = "pretty")

# convert to a data.frame for merging
occupation_df <- data.frame(paste0(str_pad(occupation@geography$state, 2, "left", pad="0"), 
                               str_pad(occupation@geography$county, 3, "left", pad="0")), 
                        occupation@estimate, 
                        stringsAsFactors = FALSE)
names(occupation_df)[1] <- 'geoid'

# Merge all demographic data together
demographic.total <- left_join(race_df, left_join(income_df, left_join(employment_df, occupation_df)))

```

<h2><b> Manipulating The Data </b></h2>


```{r, manipulate data, echo=FALSE, message=FALSE, results='hide', warning=FALSE}

# Join demographic data to election results
election.results.demog <- left_join(election.results.final,
                                    demographic.total,
                                    by = c('fips_fixed' = 'geoid'))

# Write file to csv
write.csv(election.results.demog, 'election_results_with_demographics.csv', row.names = FALSE)

# Join columns from df to cty
map.df <- left_join(cty.df,
                    election.results.demog,
                    by = c('GEOID10' = 'fips_fixed'))

```

```{r, visualization, fig.width=6, fig.height=10}

## Build Plot

# Remove AK and HI
plt.dat <- map.df %>%
  filter(STATEFP10 != '02',
         STATEFP10 != '15',
         STATEFP10 != '43')

# Identify county winner for faceting down the road
plt.dat$winner <- sapply(plt.dat$trump, function(x) { 
  
  if (is.na(x)) {
    NA
  } else if (x > .5) {
      'Trump'
  } else {
    'Clinton'
  }
})
  
# Build plot
plt <- ggplot(plt.dat, aes(x = long, y = lat, group = group, fill = 100*trump)) +
  scale_fill_gradient2(low = "#008abc",
                      mid = "#ffffff",
                      high = "#c71f16",
                      midpoint = 50,
                      na.value = "#A6A5A5") + 
  geom_polygon(colour = '#f0f2f3', size = 0.1) +
  coord_equal() + 
  labs(title = 'County Level Election Results',
       subtitle = 'Shading is based on the share of votes for counties won by Clinton (blue) and Trump (red)') +
  theme(axis.text = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = 'none')

# Save
ggsave(filename = 'county_results.png',
       plot = plt,
       type = 'cairo-png',
       height = 6,
       width = 12,
       units = 'in')


```
